/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class asset_id extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"asset_id\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"platform_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tms_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  @Deprecated public java.lang.CharSequence platform_id;
  @Deprecated public java.lang.CharSequence tms_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return platform_id;
    case 1: return tms_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: platform_id = (java.lang.CharSequence)value$; break;
    case 1: tms_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'platform_id' field.
   */
  public java.lang.CharSequence getPlatformId() {
    return platform_id;
  }

  /**
   * Sets the value of the 'platform_id' field.
   * @param value the value to set.
   */
  public void setPlatformId(java.lang.CharSequence value) {
    this.platform_id = value;
  }

  /**
   * Gets the value of the 'tms_id' field.
   */
  public java.lang.CharSequence getTmsId() {
    return tms_id;
  }

  /**
   * Sets the value of the 'tms_id' field.
   * @param value the value to set.
   */
  public void setTmsId(java.lang.CharSequence value) {
    this.tms_id = value;
  }

  /** Creates a new asset_id RecordBuilder */
  public static com.twc.bigdata.views.avro.asset_id.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.asset_id.Builder();
  }
  
  /** Creates a new asset_id RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.asset_id.Builder newBuilder(com.twc.bigdata.views.avro.asset_id.Builder other) {
    return new com.twc.bigdata.views.avro.asset_id.Builder(other);
  }
  
  /** Creates a new asset_id RecordBuilder by copying an existing asset_id instance */
  public static com.twc.bigdata.views.avro.asset_id.Builder newBuilder(com.twc.bigdata.views.avro.asset_id other) {
    return new com.twc.bigdata.views.avro.asset_id.Builder(other);
  }
  
  /**
   * RecordBuilder for asset_id instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<asset_id>
    implements org.apache.avro.data.RecordBuilder<asset_id> {

    private java.lang.CharSequence platform_id;
    private java.lang.CharSequence tms_id;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.asset_id.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.asset_id.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing asset_id instance */
    private Builder(com.twc.bigdata.views.avro.asset_id other) {
            super(com.twc.bigdata.views.avro.asset_id.SCHEMA$);
      if (isValidValue(fields()[0], other.platform_id)) {
        this.platform_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.platform_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tms_id)) {
        this.tms_id = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.tms_id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'platform_id' field */
    public java.lang.CharSequence getPlatformId() {
      return platform_id;
    }
    
    /** Sets the value of the 'platform_id' field */
    public com.twc.bigdata.views.avro.asset_id.Builder setPlatformId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.platform_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'platform_id' field has been set */
    public boolean hasPlatformId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'platform_id' field */
    public com.twc.bigdata.views.avro.asset_id.Builder clearPlatformId() {
      platform_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'tms_id' field */
    public java.lang.CharSequence getTmsId() {
      return tms_id;
    }
    
    /** Sets the value of the 'tms_id' field */
    public com.twc.bigdata.views.avro.asset_id.Builder setTmsId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tms_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'tms_id' field has been set */
    public boolean hasTmsId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'tms_id' field */
    public com.twc.bigdata.views.avro.asset_id.Builder clearTmsId() {
      tms_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public asset_id build() {
      try {
        asset_id record = new asset_id();
        record.platform_id = fieldSetFlags()[0] ? this.platform_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tms_id = fieldSetFlags()[1] ? this.tms_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
