/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class content_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"content_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"asset_id\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"asset_id\",\"fields\":[{\"name\":\"platform_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tms_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}]},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"episode_title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"run_time\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"asset_type\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"content_type\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"callsign\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"tv_rating\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"genres\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"vod_content_info\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"vod_content_info\",\"fields\":[{\"name\":\"product_provider\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"network\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"live_content_info\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"live_content_info\",\"fields\":[{\"name\":\"tms_channel_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"channel_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gm_time\",\"type\":[\"long\",\"null\"],\"default\":0}]}],\"default\":null}]}");
  @Deprecated public com.twc.bigdata.views.avro.asset_id asset_id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence episode_title;
  @Deprecated public java.lang.CharSequence run_time;
  @Deprecated public java.lang.CharSequence asset_type;
  @Deprecated public java.lang.CharSequence content_type;
  @Deprecated public java.lang.CharSequence callsign;
  @Deprecated public java.lang.CharSequence tv_rating;
  @Deprecated public java.util.List<java.lang.CharSequence> genres;
  @Deprecated public com.twc.bigdata.views.avro.vod_content_info vod_content_info;
  @Deprecated public com.twc.bigdata.views.avro.live_content_info live_content_info;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return asset_id;
    case 1: return title;
    case 2: return episode_title;
    case 3: return run_time;
    case 4: return asset_type;
    case 5: return content_type;
    case 6: return callsign;
    case 7: return tv_rating;
    case 8: return genres;
    case 9: return vod_content_info;
    case 10: return live_content_info;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: asset_id = (com.twc.bigdata.views.avro.asset_id)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: episode_title = (java.lang.CharSequence)value$; break;
    case 3: run_time = (java.lang.CharSequence)value$; break;
    case 4: asset_type = (java.lang.CharSequence)value$; break;
    case 5: content_type = (java.lang.CharSequence)value$; break;
    case 6: callsign = (java.lang.CharSequence)value$; break;
    case 7: tv_rating = (java.lang.CharSequence)value$; break;
    case 8: genres = (java.util.List<java.lang.CharSequence>)value$; break;
    case 9: vod_content_info = (com.twc.bigdata.views.avro.vod_content_info)value$; break;
    case 10: live_content_info = (com.twc.bigdata.views.avro.live_content_info)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'asset_id' field.
   */
  public com.twc.bigdata.views.avro.asset_id getAssetId() {
    return asset_id;
  }

  /**
   * Sets the value of the 'asset_id' field.
   * @param value the value to set.
   */
  public void setAssetId(com.twc.bigdata.views.avro.asset_id value) {
    this.asset_id = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'episode_title' field.
   */
  public java.lang.CharSequence getEpisodeTitle() {
    return episode_title;
  }

  /**
   * Sets the value of the 'episode_title' field.
   * @param value the value to set.
   */
  public void setEpisodeTitle(java.lang.CharSequence value) {
    this.episode_title = value;
  }

  /**
   * Gets the value of the 'run_time' field.
   */
  public java.lang.CharSequence getRunTime() {
    return run_time;
  }

  /**
   * Sets the value of the 'run_time' field.
   * @param value the value to set.
   */
  public void setRunTime(java.lang.CharSequence value) {
    this.run_time = value;
  }

  /**
   * Gets the value of the 'asset_type' field.
   */
  public java.lang.CharSequence getAssetType() {
    return asset_type;
  }

  /**
   * Sets the value of the 'asset_type' field.
   * @param value the value to set.
   */
  public void setAssetType(java.lang.CharSequence value) {
    this.asset_type = value;
  }

  /**
   * Gets the value of the 'content_type' field.
   */
  public java.lang.CharSequence getContentType() {
    return content_type;
  }

  /**
   * Sets the value of the 'content_type' field.
   * @param value the value to set.
   */
  public void setContentType(java.lang.CharSequence value) {
    this.content_type = value;
  }

  /**
   * Gets the value of the 'callsign' field.
   */
  public java.lang.CharSequence getCallsign() {
    return callsign;
  }

  /**
   * Sets the value of the 'callsign' field.
   * @param value the value to set.
   */
  public void setCallsign(java.lang.CharSequence value) {
    this.callsign = value;
  }

  /**
   * Gets the value of the 'tv_rating' field.
   */
  public java.lang.CharSequence getTvRating() {
    return tv_rating;
  }

  /**
   * Sets the value of the 'tv_rating' field.
   * @param value the value to set.
   */
  public void setTvRating(java.lang.CharSequence value) {
    this.tv_rating = value;
  }

  /**
   * Gets the value of the 'genres' field.
   */
  public java.util.List<java.lang.CharSequence> getGenres() {
    return genres;
  }

  /**
   * Sets the value of the 'genres' field.
   * @param value the value to set.
   */
  public void setGenres(java.util.List<java.lang.CharSequence> value) {
    this.genres = value;
  }

  /**
   * Gets the value of the 'vod_content_info' field.
   */
  public com.twc.bigdata.views.avro.vod_content_info getVodContentInfo() {
    return vod_content_info;
  }

  /**
   * Sets the value of the 'vod_content_info' field.
   * @param value the value to set.
   */
  public void setVodContentInfo(com.twc.bigdata.views.avro.vod_content_info value) {
    this.vod_content_info = value;
  }

  /**
   * Gets the value of the 'live_content_info' field.
   */
  public com.twc.bigdata.views.avro.live_content_info getLiveContentInfo() {
    return live_content_info;
  }

  /**
   * Sets the value of the 'live_content_info' field.
   * @param value the value to set.
   */
  public void setLiveContentInfo(com.twc.bigdata.views.avro.live_content_info value) {
    this.live_content_info = value;
  }

  /** Creates a new content_info RecordBuilder */
  public static com.twc.bigdata.views.avro.content_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.content_info.Builder();
  }
  
  /** Creates a new content_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.content_info.Builder newBuilder(com.twc.bigdata.views.avro.content_info.Builder other) {
    return new com.twc.bigdata.views.avro.content_info.Builder(other);
  }
  
  /** Creates a new content_info RecordBuilder by copying an existing content_info instance */
  public static com.twc.bigdata.views.avro.content_info.Builder newBuilder(com.twc.bigdata.views.avro.content_info other) {
    return new com.twc.bigdata.views.avro.content_info.Builder(other);
  }
  
  /**
   * RecordBuilder for content_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<content_info>
    implements org.apache.avro.data.RecordBuilder<content_info> {

    private com.twc.bigdata.views.avro.asset_id asset_id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence episode_title;
    private java.lang.CharSequence run_time;
    private java.lang.CharSequence asset_type;
    private java.lang.CharSequence content_type;
    private java.lang.CharSequence callsign;
    private java.lang.CharSequence tv_rating;
    private java.util.List<java.lang.CharSequence> genres;
    private com.twc.bigdata.views.avro.vod_content_info vod_content_info;
    private com.twc.bigdata.views.avro.live_content_info live_content_info;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.content_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.content_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing content_info instance */
    private Builder(com.twc.bigdata.views.avro.content_info other) {
            super(com.twc.bigdata.views.avro.content_info.SCHEMA$);
      if (isValidValue(fields()[0], other.asset_id)) {
        this.asset_id = (com.twc.bigdata.views.avro.asset_id) data().deepCopy(fields()[0].schema(), other.asset_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.episode_title)) {
        this.episode_title = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.episode_title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.run_time)) {
        this.run_time = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.run_time);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.asset_type)) {
        this.asset_type = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.asset_type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.content_type)) {
        this.content_type = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.content_type);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.callsign)) {
        this.callsign = (java.lang.CharSequence) data().deepCopy(fields()[6].schema(), other.callsign);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.tv_rating)) {
        this.tv_rating = (java.lang.CharSequence) data().deepCopy(fields()[7].schema(), other.tv_rating);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.genres)) {
        this.genres = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[8].schema(), other.genres);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.vod_content_info)) {
        this.vod_content_info = (com.twc.bigdata.views.avro.vod_content_info) data().deepCopy(fields()[9].schema(), other.vod_content_info);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.live_content_info)) {
        this.live_content_info = (com.twc.bigdata.views.avro.live_content_info) data().deepCopy(fields()[10].schema(), other.live_content_info);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'asset_id' field */
    public com.twc.bigdata.views.avro.asset_id getAssetId() {
      return asset_id;
    }
    
    /** Sets the value of the 'asset_id' field */
    public com.twc.bigdata.views.avro.content_info.Builder setAssetId(com.twc.bigdata.views.avro.asset_id value) {
      validate(fields()[0], value);
      this.asset_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'asset_id' field has been set */
    public boolean hasAssetId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'asset_id' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearAssetId() {
      asset_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public com.twc.bigdata.views.avro.content_info.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'episode_title' field */
    public java.lang.CharSequence getEpisodeTitle() {
      return episode_title;
    }
    
    /** Sets the value of the 'episode_title' field */
    public com.twc.bigdata.views.avro.content_info.Builder setEpisodeTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.episode_title = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'episode_title' field has been set */
    public boolean hasEpisodeTitle() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'episode_title' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearEpisodeTitle() {
      episode_title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'run_time' field */
    public java.lang.CharSequence getRunTime() {
      return run_time;
    }
    
    /** Sets the value of the 'run_time' field */
    public com.twc.bigdata.views.avro.content_info.Builder setRunTime(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.run_time = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'run_time' field has been set */
    public boolean hasRunTime() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'run_time' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearRunTime() {
      run_time = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'asset_type' field */
    public java.lang.CharSequence getAssetType() {
      return asset_type;
    }
    
    /** Sets the value of the 'asset_type' field */
    public com.twc.bigdata.views.avro.content_info.Builder setAssetType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.asset_type = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'asset_type' field has been set */
    public boolean hasAssetType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'asset_type' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearAssetType() {
      asset_type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'content_type' field */
    public java.lang.CharSequence getContentType() {
      return content_type;
    }
    
    /** Sets the value of the 'content_type' field */
    public com.twc.bigdata.views.avro.content_info.Builder setContentType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.content_type = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'content_type' field has been set */
    public boolean hasContentType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'content_type' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearContentType() {
      content_type = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'callsign' field */
    public java.lang.CharSequence getCallsign() {
      return callsign;
    }
    
    /** Sets the value of the 'callsign' field */
    public com.twc.bigdata.views.avro.content_info.Builder setCallsign(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.callsign = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'callsign' field has been set */
    public boolean hasCallsign() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'callsign' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearCallsign() {
      callsign = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'tv_rating' field */
    public java.lang.CharSequence getTvRating() {
      return tv_rating;
    }
    
    /** Sets the value of the 'tv_rating' field */
    public com.twc.bigdata.views.avro.content_info.Builder setTvRating(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.tv_rating = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'tv_rating' field has been set */
    public boolean hasTvRating() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'tv_rating' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearTvRating() {
      tv_rating = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'genres' field */
    public java.util.List<java.lang.CharSequence> getGenres() {
      return genres;
    }
    
    /** Sets the value of the 'genres' field */
    public com.twc.bigdata.views.avro.content_info.Builder setGenres(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[8], value);
      this.genres = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'genres' field has been set */
    public boolean hasGenres() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'genres' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearGenres() {
      genres = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'vod_content_info' field */
    public com.twc.bigdata.views.avro.vod_content_info getVodContentInfo() {
      return vod_content_info;
    }
    
    /** Sets the value of the 'vod_content_info' field */
    public com.twc.bigdata.views.avro.content_info.Builder setVodContentInfo(com.twc.bigdata.views.avro.vod_content_info value) {
      validate(fields()[9], value);
      this.vod_content_info = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'vod_content_info' field has been set */
    public boolean hasVodContentInfo() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'vod_content_info' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearVodContentInfo() {
      vod_content_info = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'live_content_info' field */
    public com.twc.bigdata.views.avro.live_content_info getLiveContentInfo() {
      return live_content_info;
    }
    
    /** Sets the value of the 'live_content_info' field */
    public com.twc.bigdata.views.avro.content_info.Builder setLiveContentInfo(com.twc.bigdata.views.avro.live_content_info value) {
      validate(fields()[10], value);
      this.live_content_info = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'live_content_info' field has been set */
    public boolean hasLiveContentInfo() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'live_content_info' field */
    public com.twc.bigdata.views.avro.content_info.Builder clearLiveContentInfo() {
      live_content_info = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public content_info build() {
      try {
        content_info record = new content_info();
        record.asset_id = fieldSetFlags()[0] ? this.asset_id : (com.twc.bigdata.views.avro.asset_id) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.episode_title = fieldSetFlags()[2] ? this.episode_title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.run_time = fieldSetFlags()[3] ? this.run_time : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.asset_type = fieldSetFlags()[4] ? this.asset_type : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.content_type = fieldSetFlags()[5] ? this.content_type : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.callsign = fieldSetFlags()[6] ? this.callsign : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.tv_rating = fieldSetFlags()[7] ? this.tv_rating : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.genres = fieldSetFlags()[8] ? this.genres : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[8]);
        record.vod_content_info = fieldSetFlags()[9] ? this.vod_content_info : (com.twc.bigdata.views.avro.vod_content_info) defaultValue(fields()[9]);
        record.live_content_info = fieldSetFlags()[10] ? this.live_content_info : (com.twc.bigdata.views.avro.live_content_info) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
