/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class content_discovery extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"content_discovery\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"content_access\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"triggered_by\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"search_term\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"search_index\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"pod_index\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"pod_category\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"network_name\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  @Deprecated public java.lang.CharSequence content_access;
  @Deprecated public java.lang.CharSequence triggered_by;
  @Deprecated public java.lang.CharSequence search_term;
  @Deprecated public java.lang.Integer search_index;
  @Deprecated public java.lang.Integer pod_index;
  @Deprecated public java.lang.CharSequence pod_category;
  @Deprecated public java.lang.CharSequence network_name;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return content_access;
    case 1: return triggered_by;
    case 2: return search_term;
    case 3: return search_index;
    case 4: return pod_index;
    case 5: return pod_category;
    case 6: return network_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: content_access = (java.lang.CharSequence)value$; break;
    case 1: triggered_by = (java.lang.CharSequence)value$; break;
    case 2: search_term = (java.lang.CharSequence)value$; break;
    case 3: search_index = (java.lang.Integer)value$; break;
    case 4: pod_index = (java.lang.Integer)value$; break;
    case 5: pod_category = (java.lang.CharSequence)value$; break;
    case 6: network_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'content_access' field.
   */
  public java.lang.CharSequence getContentAccess() {
    return content_access;
  }

  /**
   * Sets the value of the 'content_access' field.
   * @param value the value to set.
   */
  public void setContentAccess(java.lang.CharSequence value) {
    this.content_access = value;
  }

  /**
   * Gets the value of the 'triggered_by' field.
   */
  public java.lang.CharSequence getTriggeredBy() {
    return triggered_by;
  }

  /**
   * Sets the value of the 'triggered_by' field.
   * @param value the value to set.
   */
  public void setTriggeredBy(java.lang.CharSequence value) {
    this.triggered_by = value;
  }

  /**
   * Gets the value of the 'search_term' field.
   */
  public java.lang.CharSequence getSearchTerm() {
    return search_term;
  }

  /**
   * Sets the value of the 'search_term' field.
   * @param value the value to set.
   */
  public void setSearchTerm(java.lang.CharSequence value) {
    this.search_term = value;
  }

  /**
   * Gets the value of the 'search_index' field.
   */
  public java.lang.Integer getSearchIndex() {
    return search_index;
  }

  /**
   * Sets the value of the 'search_index' field.
   * @param value the value to set.
   */
  public void setSearchIndex(java.lang.Integer value) {
    this.search_index = value;
  }

  /**
   * Gets the value of the 'pod_index' field.
   */
  public java.lang.Integer getPodIndex() {
    return pod_index;
  }

  /**
   * Sets the value of the 'pod_index' field.
   * @param value the value to set.
   */
  public void setPodIndex(java.lang.Integer value) {
    this.pod_index = value;
  }

  /**
   * Gets the value of the 'pod_category' field.
   */
  public java.lang.CharSequence getPodCategory() {
    return pod_category;
  }

  /**
   * Sets the value of the 'pod_category' field.
   * @param value the value to set.
   */
  public void setPodCategory(java.lang.CharSequence value) {
    this.pod_category = value;
  }

  /**
   * Gets the value of the 'network_name' field.
   */
  public java.lang.CharSequence getNetworkName() {
    return network_name;
  }

  /**
   * Sets the value of the 'network_name' field.
   * @param value the value to set.
   */
  public void setNetworkName(java.lang.CharSequence value) {
    this.network_name = value;
  }

  /** Creates a new content_discovery RecordBuilder */
  public static com.twc.bigdata.views.avro.content_discovery.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.content_discovery.Builder();
  }
  
  /** Creates a new content_discovery RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.content_discovery.Builder newBuilder(com.twc.bigdata.views.avro.content_discovery.Builder other) {
    return new com.twc.bigdata.views.avro.content_discovery.Builder(other);
  }
  
  /** Creates a new content_discovery RecordBuilder by copying an existing content_discovery instance */
  public static com.twc.bigdata.views.avro.content_discovery.Builder newBuilder(com.twc.bigdata.views.avro.content_discovery other) {
    return new com.twc.bigdata.views.avro.content_discovery.Builder(other);
  }
  
  /**
   * RecordBuilder for content_discovery instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<content_discovery>
    implements org.apache.avro.data.RecordBuilder<content_discovery> {

    private java.lang.CharSequence content_access;
    private java.lang.CharSequence triggered_by;
    private java.lang.CharSequence search_term;
    private java.lang.Integer search_index;
    private java.lang.Integer pod_index;
    private java.lang.CharSequence pod_category;
    private java.lang.CharSequence network_name;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.content_discovery.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.content_discovery.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing content_discovery instance */
    private Builder(com.twc.bigdata.views.avro.content_discovery other) {
            super(com.twc.bigdata.views.avro.content_discovery.SCHEMA$);
      if (isValidValue(fields()[0], other.content_access)) {
        this.content_access = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.content_access);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.triggered_by)) {
        this.triggered_by = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.triggered_by);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.search_term)) {
        this.search_term = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.search_term);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.search_index)) {
        this.search_index = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.search_index);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pod_index)) {
        this.pod_index = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.pod_index);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.pod_category)) {
        this.pod_category = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.pod_category);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.network_name)) {
        this.network_name = (java.lang.CharSequence) data().deepCopy(fields()[6].schema(), other.network_name);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'content_access' field */
    public java.lang.CharSequence getContentAccess() {
      return content_access;
    }
    
    /** Sets the value of the 'content_access' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setContentAccess(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.content_access = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'content_access' field has been set */
    public boolean hasContentAccess() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'content_access' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearContentAccess() {
      content_access = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'triggered_by' field */
    public java.lang.CharSequence getTriggeredBy() {
      return triggered_by;
    }
    
    /** Sets the value of the 'triggered_by' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setTriggeredBy(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.triggered_by = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'triggered_by' field has been set */
    public boolean hasTriggeredBy() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'triggered_by' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearTriggeredBy() {
      triggered_by = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'search_term' field */
    public java.lang.CharSequence getSearchTerm() {
      return search_term;
    }
    
    /** Sets the value of the 'search_term' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setSearchTerm(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.search_term = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'search_term' field has been set */
    public boolean hasSearchTerm() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'search_term' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearSearchTerm() {
      search_term = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'search_index' field */
    public java.lang.Integer getSearchIndex() {
      return search_index;
    }
    
    /** Sets the value of the 'search_index' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setSearchIndex(java.lang.Integer value) {
      validate(fields()[3], value);
      this.search_index = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'search_index' field has been set */
    public boolean hasSearchIndex() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'search_index' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearSearchIndex() {
      search_index = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'pod_index' field */
    public java.lang.Integer getPodIndex() {
      return pod_index;
    }
    
    /** Sets the value of the 'pod_index' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setPodIndex(java.lang.Integer value) {
      validate(fields()[4], value);
      this.pod_index = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'pod_index' field has been set */
    public boolean hasPodIndex() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'pod_index' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearPodIndex() {
      pod_index = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'pod_category' field */
    public java.lang.CharSequence getPodCategory() {
      return pod_category;
    }
    
    /** Sets the value of the 'pod_category' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setPodCategory(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.pod_category = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'pod_category' field has been set */
    public boolean hasPodCategory() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'pod_category' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearPodCategory() {
      pod_category = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'network_name' field */
    public java.lang.CharSequence getNetworkName() {
      return network_name;
    }
    
    /** Sets the value of the 'network_name' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder setNetworkName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.network_name = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'network_name' field has been set */
    public boolean hasNetworkName() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'network_name' field */
    public com.twc.bigdata.views.avro.content_discovery.Builder clearNetworkName() {
      network_name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public content_discovery build() {
      try {
        content_discovery record = new content_discovery();
        record.content_access = fieldSetFlags()[0] ? this.content_access : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.triggered_by = fieldSetFlags()[1] ? this.triggered_by : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.search_term = fieldSetFlags()[2] ? this.search_term : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.search_index = fieldSetFlags()[3] ? this.search_index : (java.lang.Integer) defaultValue(fields()[3]);
        record.pod_index = fieldSetFlags()[4] ? this.pod_index : (java.lang.Integer) defaultValue(fields()[4]);
        record.pod_category = fieldSetFlags()[5] ? this.pod_category : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.network_name = fieldSetFlags()[6] ? this.network_name : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
