/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class delivery_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"delivery_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"delivery_format\",\"type\":[\"null\",\"string\"]},{\"name\":\"definition\",\"type\":[\"null\",\"string\"]},{\"name\":\"network_provider\",\"type\":[\"null\",\"string\"]},{\"name\":\"out_of_home\",\"type\":[\"null\",\"boolean\"],\"default\":null}]}");
  @Deprecated public java.lang.CharSequence delivery_format;
  @Deprecated public java.lang.CharSequence definition;
  @Deprecated public java.lang.CharSequence network_provider;
  @Deprecated public java.lang.Boolean out_of_home;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return delivery_format;
    case 1: return definition;
    case 2: return network_provider;
    case 3: return out_of_home;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: delivery_format = (java.lang.CharSequence)value$; break;
    case 1: definition = (java.lang.CharSequence)value$; break;
    case 2: network_provider = (java.lang.CharSequence)value$; break;
    case 3: out_of_home = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'delivery_format' field.
   */
  public java.lang.CharSequence getDeliveryFormat() {
    return delivery_format;
  }

  /**
   * Sets the value of the 'delivery_format' field.
   * @param value the value to set.
   */
  public void setDeliveryFormat(java.lang.CharSequence value) {
    this.delivery_format = value;
  }

  /**
   * Gets the value of the 'definition' field.
   */
  public java.lang.CharSequence getDefinition() {
    return definition;
  }

  /**
   * Sets the value of the 'definition' field.
   * @param value the value to set.
   */
  public void setDefinition(java.lang.CharSequence value) {
    this.definition = value;
  }

  /**
   * Gets the value of the 'network_provider' field.
   */
  public java.lang.CharSequence getNetworkProvider() {
    return network_provider;
  }

  /**
   * Sets the value of the 'network_provider' field.
   * @param value the value to set.
   */
  public void setNetworkProvider(java.lang.CharSequence value) {
    this.network_provider = value;
  }

  /**
   * Gets the value of the 'out_of_home' field.
   */
  public java.lang.Boolean getOutOfHome() {
    return out_of_home;
  }

  /**
   * Sets the value of the 'out_of_home' field.
   * @param value the value to set.
   */
  public void setOutOfHome(java.lang.Boolean value) {
    this.out_of_home = value;
  }

  /** Creates a new delivery_info RecordBuilder */
  public static com.twc.bigdata.views.avro.delivery_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.delivery_info.Builder();
  }
  
  /** Creates a new delivery_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.delivery_info.Builder newBuilder(com.twc.bigdata.views.avro.delivery_info.Builder other) {
    return new com.twc.bigdata.views.avro.delivery_info.Builder(other);
  }
  
  /** Creates a new delivery_info RecordBuilder by copying an existing delivery_info instance */
  public static com.twc.bigdata.views.avro.delivery_info.Builder newBuilder(com.twc.bigdata.views.avro.delivery_info other) {
    return new com.twc.bigdata.views.avro.delivery_info.Builder(other);
  }
  
  /**
   * RecordBuilder for delivery_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<delivery_info>
    implements org.apache.avro.data.RecordBuilder<delivery_info> {

    private java.lang.CharSequence delivery_format;
    private java.lang.CharSequence definition;
    private java.lang.CharSequence network_provider;
    private java.lang.Boolean out_of_home;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.delivery_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.delivery_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing delivery_info instance */
    private Builder(com.twc.bigdata.views.avro.delivery_info other) {
            super(com.twc.bigdata.views.avro.delivery_info.SCHEMA$);
      if (isValidValue(fields()[0], other.delivery_format)) {
        this.delivery_format = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.delivery_format);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.definition)) {
        this.definition = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.definition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.network_provider)) {
        this.network_provider = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.network_provider);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.out_of_home)) {
        this.out_of_home = (java.lang.Boolean) data().deepCopy(fields()[3].schema(), other.out_of_home);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'delivery_format' field */
    public java.lang.CharSequence getDeliveryFormat() {
      return delivery_format;
    }
    
    /** Sets the value of the 'delivery_format' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder setDeliveryFormat(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.delivery_format = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'delivery_format' field has been set */
    public boolean hasDeliveryFormat() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'delivery_format' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder clearDeliveryFormat() {
      delivery_format = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'definition' field */
    public java.lang.CharSequence getDefinition() {
      return definition;
    }
    
    /** Sets the value of the 'definition' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder setDefinition(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.definition = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'definition' field has been set */
    public boolean hasDefinition() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'definition' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder clearDefinition() {
      definition = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'network_provider' field */
    public java.lang.CharSequence getNetworkProvider() {
      return network_provider;
    }
    
    /** Sets the value of the 'network_provider' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder setNetworkProvider(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.network_provider = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'network_provider' field has been set */
    public boolean hasNetworkProvider() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'network_provider' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder clearNetworkProvider() {
      network_provider = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'out_of_home' field */
    public java.lang.Boolean getOutOfHome() {
      return out_of_home;
    }
    
    /** Sets the value of the 'out_of_home' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder setOutOfHome(java.lang.Boolean value) {
      validate(fields()[3], value);
      this.out_of_home = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'out_of_home' field has been set */
    public boolean hasOutOfHome() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'out_of_home' field */
    public com.twc.bigdata.views.avro.delivery_info.Builder clearOutOfHome() {
      out_of_home = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public delivery_info build() {
      try {
        delivery_info record = new delivery_info();
        record.delivery_format = fieldSetFlags()[0] ? this.delivery_format : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.definition = fieldSetFlags()[1] ? this.definition : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.network_provider = fieldSetFlags()[2] ? this.network_provider : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.out_of_home = fieldSetFlags()[3] ? this.out_of_home : (java.lang.Boolean) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
