/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class identifiers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"identifiers\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"view_id\",\"type\":\"string\"},{\"name\":\"content_view_id\",\"type\":\"int\"},{\"name\":\"session_id\",\"type\":\"string\"},{\"name\":\"pi_session_id\",\"type\":\"string\"},{\"name\":\"playback_type\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence view_id;
  @Deprecated public int content_view_id;
  @Deprecated public java.lang.CharSequence session_id;
  @Deprecated public java.lang.CharSequence pi_session_id;
  @Deprecated public java.lang.CharSequence playback_type;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return view_id;
    case 1: return content_view_id;
    case 2: return session_id;
    case 3: return pi_session_id;
    case 4: return playback_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: view_id = (java.lang.CharSequence)value$; break;
    case 1: content_view_id = (java.lang.Integer)value$; break;
    case 2: session_id = (java.lang.CharSequence)value$; break;
    case 3: pi_session_id = (java.lang.CharSequence)value$; break;
    case 4: playback_type = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'view_id' field.
   */
  public java.lang.CharSequence getViewId() {
    return view_id;
  }

  /**
   * Sets the value of the 'view_id' field.
   * @param value the value to set.
   */
  public void setViewId(java.lang.CharSequence value) {
    this.view_id = value;
  }

  /**
   * Gets the value of the 'content_view_id' field.
   */
  public java.lang.Integer getContentViewId() {
    return content_view_id;
  }

  /**
   * Sets the value of the 'content_view_id' field.
   * @param value the value to set.
   */
  public void setContentViewId(java.lang.Integer value) {
    this.content_view_id = value;
  }

  /**
   * Gets the value of the 'session_id' field.
   */
  public java.lang.CharSequence getSessionId() {
    return session_id;
  }

  /**
   * Sets the value of the 'session_id' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.CharSequence value) {
    this.session_id = value;
  }

  /**
   * Gets the value of the 'pi_session_id' field.
   */
  public java.lang.CharSequence getPiSessionId() {
    return pi_session_id;
  }

  /**
   * Sets the value of the 'pi_session_id' field.
   * @param value the value to set.
   */
  public void setPiSessionId(java.lang.CharSequence value) {
    this.pi_session_id = value;
  }

  /**
   * Gets the value of the 'playback_type' field.
   */
  public java.lang.CharSequence getPlaybackType() {
    return playback_type;
  }

  /**
   * Sets the value of the 'playback_type' field.
   * @param value the value to set.
   */
  public void setPlaybackType(java.lang.CharSequence value) {
    this.playback_type = value;
  }

  /** Creates a new identifiers RecordBuilder */
  public static com.twc.bigdata.views.avro.identifiers.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.identifiers.Builder();
  }
  
  /** Creates a new identifiers RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.identifiers.Builder newBuilder(com.twc.bigdata.views.avro.identifiers.Builder other) {
    return new com.twc.bigdata.views.avro.identifiers.Builder(other);
  }
  
  /** Creates a new identifiers RecordBuilder by copying an existing identifiers instance */
  public static com.twc.bigdata.views.avro.identifiers.Builder newBuilder(com.twc.bigdata.views.avro.identifiers other) {
    return new com.twc.bigdata.views.avro.identifiers.Builder(other);
  }
  
  /**
   * RecordBuilder for identifiers instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<identifiers>
    implements org.apache.avro.data.RecordBuilder<identifiers> {

    private java.lang.CharSequence view_id;
    private int content_view_id;
    private java.lang.CharSequence session_id;
    private java.lang.CharSequence pi_session_id;
    private java.lang.CharSequence playback_type;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.identifiers.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.identifiers.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing identifiers instance */
    private Builder(com.twc.bigdata.views.avro.identifiers other) {
            super(com.twc.bigdata.views.avro.identifiers.SCHEMA$);
      if (isValidValue(fields()[0], other.view_id)) {
        this.view_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.view_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content_view_id)) {
        this.content_view_id = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.content_view_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.session_id)) {
        this.session_id = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.session_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pi_session_id)) {
        this.pi_session_id = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.pi_session_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.playback_type)) {
        this.playback_type = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.playback_type);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'view_id' field */
    public java.lang.CharSequence getViewId() {
      return view_id;
    }
    
    /** Sets the value of the 'view_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder setViewId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.view_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'view_id' field has been set */
    public boolean hasViewId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'view_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder clearViewId() {
      view_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'content_view_id' field */
    public java.lang.Integer getContentViewId() {
      return content_view_id;
    }
    
    /** Sets the value of the 'content_view_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder setContentViewId(int value) {
      validate(fields()[1], value);
      this.content_view_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'content_view_id' field has been set */
    public boolean hasContentViewId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'content_view_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder clearContentViewId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'session_id' field */
    public java.lang.CharSequence getSessionId() {
      return session_id;
    }
    
    /** Sets the value of the 'session_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder setSessionId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.session_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'session_id' field has been set */
    public boolean hasSessionId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'session_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder clearSessionId() {
      session_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'pi_session_id' field */
    public java.lang.CharSequence getPiSessionId() {
      return pi_session_id;
    }
    
    /** Sets the value of the 'pi_session_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder setPiSessionId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.pi_session_id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'pi_session_id' field has been set */
    public boolean hasPiSessionId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'pi_session_id' field */
    public com.twc.bigdata.views.avro.identifiers.Builder clearPiSessionId() {
      pi_session_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'playback_type' field */
    public java.lang.CharSequence getPlaybackType() {
      return playback_type;
    }
    
    /** Sets the value of the 'playback_type' field */
    public com.twc.bigdata.views.avro.identifiers.Builder setPlaybackType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.playback_type = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'playback_type' field has been set */
    public boolean hasPlaybackType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'playback_type' field */
    public com.twc.bigdata.views.avro.identifiers.Builder clearPlaybackType() {
      playback_type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public identifiers build() {
      try {
        identifiers record = new identifiers();
        record.view_id = fieldSetFlags()[0] ? this.view_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content_view_id = fieldSetFlags()[1] ? this.content_view_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.session_id = fieldSetFlags()[2] ? this.session_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.pi_session_id = fieldSetFlags()[3] ? this.pi_session_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.playback_type = fieldSetFlags()[4] ? this.playback_type : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
