/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class live_content_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"live_content_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"tms_channel_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"channel_number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gm_time\",\"type\":[\"long\",\"null\"],\"default\":0}]}");
  @Deprecated public java.lang.CharSequence tms_channel_id;
  @Deprecated public java.lang.CharSequence channel_number;
  @Deprecated public java.lang.Long gm_time;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tms_channel_id;
    case 1: return channel_number;
    case 2: return gm_time;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tms_channel_id = (java.lang.CharSequence)value$; break;
    case 1: channel_number = (java.lang.CharSequence)value$; break;
    case 2: gm_time = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tms_channel_id' field.
   */
  public java.lang.CharSequence getTmsChannelId() {
    return tms_channel_id;
  }

  /**
   * Sets the value of the 'tms_channel_id' field.
   * @param value the value to set.
   */
  public void setTmsChannelId(java.lang.CharSequence value) {
    this.tms_channel_id = value;
  }

  /**
   * Gets the value of the 'channel_number' field.
   */
  public java.lang.CharSequence getChannelNumber() {
    return channel_number;
  }

  /**
   * Sets the value of the 'channel_number' field.
   * @param value the value to set.
   */
  public void setChannelNumber(java.lang.CharSequence value) {
    this.channel_number = value;
  }

  /**
   * Gets the value of the 'gm_time' field.
   */
  public java.lang.Long getGmTime() {
    return gm_time;
  }

  /**
   * Sets the value of the 'gm_time' field.
   * @param value the value to set.
   */
  public void setGmTime(java.lang.Long value) {
    this.gm_time = value;
  }

  /** Creates a new live_content_info RecordBuilder */
  public static com.twc.bigdata.views.avro.live_content_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.live_content_info.Builder();
  }
  
  /** Creates a new live_content_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.live_content_info.Builder newBuilder(com.twc.bigdata.views.avro.live_content_info.Builder other) {
    return new com.twc.bigdata.views.avro.live_content_info.Builder(other);
  }
  
  /** Creates a new live_content_info RecordBuilder by copying an existing live_content_info instance */
  public static com.twc.bigdata.views.avro.live_content_info.Builder newBuilder(com.twc.bigdata.views.avro.live_content_info other) {
    return new com.twc.bigdata.views.avro.live_content_info.Builder(other);
  }
  
  /**
   * RecordBuilder for live_content_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<live_content_info>
    implements org.apache.avro.data.RecordBuilder<live_content_info> {

    private java.lang.CharSequence tms_channel_id;
    private java.lang.CharSequence channel_number;
    private java.lang.Long gm_time;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.live_content_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.live_content_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing live_content_info instance */
    private Builder(com.twc.bigdata.views.avro.live_content_info other) {
            super(com.twc.bigdata.views.avro.live_content_info.SCHEMA$);
      if (isValidValue(fields()[0], other.tms_channel_id)) {
        this.tms_channel_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.tms_channel_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.channel_number)) {
        this.channel_number = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.channel_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.gm_time)) {
        this.gm_time = (java.lang.Long) data().deepCopy(fields()[2].schema(), other.gm_time);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'tms_channel_id' field */
    public java.lang.CharSequence getTmsChannelId() {
      return tms_channel_id;
    }
    
    /** Sets the value of the 'tms_channel_id' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder setTmsChannelId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tms_channel_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'tms_channel_id' field has been set */
    public boolean hasTmsChannelId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'tms_channel_id' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder clearTmsChannelId() {
      tms_channel_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'channel_number' field */
    public java.lang.CharSequence getChannelNumber() {
      return channel_number;
    }
    
    /** Sets the value of the 'channel_number' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder setChannelNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.channel_number = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'channel_number' field has been set */
    public boolean hasChannelNumber() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'channel_number' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder clearChannelNumber() {
      channel_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'gm_time' field */
    public java.lang.Long getGmTime() {
      return gm_time;
    }
    
    /** Sets the value of the 'gm_time' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder setGmTime(java.lang.Long value) {
      validate(fields()[2], value);
      this.gm_time = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'gm_time' field has been set */
    public boolean hasGmTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'gm_time' field */
    public com.twc.bigdata.views.avro.live_content_info.Builder clearGmTime() {
      gm_time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public live_content_info build() {
      try {
        live_content_info record = new live_content_info();
        record.tms_channel_id = fieldSetFlags()[0] ? this.tms_channel_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.channel_number = fieldSetFlags()[1] ? this.channel_number : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.gm_time = fieldSetFlags()[2] ? this.gm_time : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
