/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class platform_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"platform_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"platform\",\"type\":\"string\"},{\"name\":\"os\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"device_model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"form_factor\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  @Deprecated public java.lang.CharSequence platform;
  @Deprecated public java.lang.CharSequence os;
  @Deprecated public java.lang.CharSequence device_model;
  @Deprecated public java.lang.CharSequence form_factor;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return platform;
    case 1: return os;
    case 2: return device_model;
    case 3: return form_factor;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: platform = (java.lang.CharSequence)value$; break;
    case 1: os = (java.lang.CharSequence)value$; break;
    case 2: device_model = (java.lang.CharSequence)value$; break;
    case 3: form_factor = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'platform' field.
   */
  public java.lang.CharSequence getPlatform() {
    return platform;
  }

  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.CharSequence value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'os' field.
   */
  public java.lang.CharSequence getOs() {
    return os;
  }

  /**
   * Sets the value of the 'os' field.
   * @param value the value to set.
   */
  public void setOs(java.lang.CharSequence value) {
    this.os = value;
  }

  /**
   * Gets the value of the 'device_model' field.
   */
  public java.lang.CharSequence getDeviceModel() {
    return device_model;
  }

  /**
   * Sets the value of the 'device_model' field.
   * @param value the value to set.
   */
  public void setDeviceModel(java.lang.CharSequence value) {
    this.device_model = value;
  }

  /**
   * Gets the value of the 'form_factor' field.
   */
  public java.lang.CharSequence getFormFactor() {
    return form_factor;
  }

  /**
   * Sets the value of the 'form_factor' field.
   * @param value the value to set.
   */
  public void setFormFactor(java.lang.CharSequence value) {
    this.form_factor = value;
  }

  /** Creates a new platform_info RecordBuilder */
  public static com.twc.bigdata.views.avro.platform_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.platform_info.Builder();
  }
  
  /** Creates a new platform_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.platform_info.Builder newBuilder(com.twc.bigdata.views.avro.platform_info.Builder other) {
    return new com.twc.bigdata.views.avro.platform_info.Builder(other);
  }
  
  /** Creates a new platform_info RecordBuilder by copying an existing platform_info instance */
  public static com.twc.bigdata.views.avro.platform_info.Builder newBuilder(com.twc.bigdata.views.avro.platform_info other) {
    return new com.twc.bigdata.views.avro.platform_info.Builder(other);
  }
  
  /**
   * RecordBuilder for platform_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<platform_info>
    implements org.apache.avro.data.RecordBuilder<platform_info> {

    private java.lang.CharSequence platform;
    private java.lang.CharSequence os;
    private java.lang.CharSequence device_model;
    private java.lang.CharSequence form_factor;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.platform_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.platform_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing platform_info instance */
    private Builder(com.twc.bigdata.views.avro.platform_info other) {
            super(com.twc.bigdata.views.avro.platform_info.SCHEMA$);
      if (isValidValue(fields()[0], other.platform)) {
        this.platform = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.platform);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.os)) {
        this.os = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.os);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.device_model)) {
        this.device_model = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.device_model);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.form_factor)) {
        this.form_factor = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.form_factor);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'platform' field */
    public java.lang.CharSequence getPlatform() {
      return platform;
    }
    
    /** Sets the value of the 'platform' field */
    public com.twc.bigdata.views.avro.platform_info.Builder setPlatform(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.platform = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'platform' field has been set */
    public boolean hasPlatform() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'platform' field */
    public com.twc.bigdata.views.avro.platform_info.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'os' field */
    public java.lang.CharSequence getOs() {
      return os;
    }
    
    /** Sets the value of the 'os' field */
    public com.twc.bigdata.views.avro.platform_info.Builder setOs(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.os = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'os' field has been set */
    public boolean hasOs() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'os' field */
    public com.twc.bigdata.views.avro.platform_info.Builder clearOs() {
      os = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'device_model' field */
    public java.lang.CharSequence getDeviceModel() {
      return device_model;
    }
    
    /** Sets the value of the 'device_model' field */
    public com.twc.bigdata.views.avro.platform_info.Builder setDeviceModel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.device_model = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'device_model' field has been set */
    public boolean hasDeviceModel() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'device_model' field */
    public com.twc.bigdata.views.avro.platform_info.Builder clearDeviceModel() {
      device_model = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'form_factor' field */
    public java.lang.CharSequence getFormFactor() {
      return form_factor;
    }
    
    /** Sets the value of the 'form_factor' field */
    public com.twc.bigdata.views.avro.platform_info.Builder setFormFactor(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.form_factor = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'form_factor' field has been set */
    public boolean hasFormFactor() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'form_factor' field */
    public com.twc.bigdata.views.avro.platform_info.Builder clearFormFactor() {
      form_factor = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public platform_info build() {
      try {
        platform_info record = new platform_info();
        record.platform = fieldSetFlags()[0] ? this.platform : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.os = fieldSetFlags()[1] ? this.os : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.device_model = fieldSetFlags()[2] ? this.device_model : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.form_factor = fieldSetFlags()[3] ? this.form_factor : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
