/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class quality_metrics extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"quality_metrics\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"seconds_below_abrx\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"startup_msec\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"abandon_time\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"count_buffer_events\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"buffer_msec\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"weighted_abr\",\"type\":[\"int\",\"null\"],\"default\":0}]}");
  @Deprecated public java.lang.Integer seconds_below_abrx;
  @Deprecated public java.lang.Integer startup_msec;
  @Deprecated public java.lang.Integer abandon_time;
  @Deprecated public java.lang.Integer count_buffer_events;
  @Deprecated public java.lang.Integer buffer_msec;
  @Deprecated public java.lang.Integer weighted_abr;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return seconds_below_abrx;
    case 1: return startup_msec;
    case 2: return abandon_time;
    case 3: return count_buffer_events;
    case 4: return buffer_msec;
    case 5: return weighted_abr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: seconds_below_abrx = (java.lang.Integer)value$; break;
    case 1: startup_msec = (java.lang.Integer)value$; break;
    case 2: abandon_time = (java.lang.Integer)value$; break;
    case 3: count_buffer_events = (java.lang.Integer)value$; break;
    case 4: buffer_msec = (java.lang.Integer)value$; break;
    case 5: weighted_abr = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'seconds_below_abrx' field.
   */
  public java.lang.Integer getSecondsBelowAbrx() {
    return seconds_below_abrx;
  }

  /**
   * Sets the value of the 'seconds_below_abrx' field.
   * @param value the value to set.
   */
  public void setSecondsBelowAbrx(java.lang.Integer value) {
    this.seconds_below_abrx = value;
  }

  /**
   * Gets the value of the 'startup_msec' field.
   */
  public java.lang.Integer getStartupMsec() {
    return startup_msec;
  }

  /**
   * Sets the value of the 'startup_msec' field.
   * @param value the value to set.
   */
  public void setStartupMsec(java.lang.Integer value) {
    this.startup_msec = value;
  }

  /**
   * Gets the value of the 'abandon_time' field.
   */
  public java.lang.Integer getAbandonTime() {
    return abandon_time;
  }

  /**
   * Sets the value of the 'abandon_time' field.
   * @param value the value to set.
   */
  public void setAbandonTime(java.lang.Integer value) {
    this.abandon_time = value;
  }

  /**
   * Gets the value of the 'count_buffer_events' field.
   */
  public java.lang.Integer getCountBufferEvents() {
    return count_buffer_events;
  }

  /**
   * Sets the value of the 'count_buffer_events' field.
   * @param value the value to set.
   */
  public void setCountBufferEvents(java.lang.Integer value) {
    this.count_buffer_events = value;
  }

  /**
   * Gets the value of the 'buffer_msec' field.
   */
  public java.lang.Integer getBufferMsec() {
    return buffer_msec;
  }

  /**
   * Sets the value of the 'buffer_msec' field.
   * @param value the value to set.
   */
  public void setBufferMsec(java.lang.Integer value) {
    this.buffer_msec = value;
  }

  /**
   * Gets the value of the 'weighted_abr' field.
   */
  public java.lang.Integer getWeightedAbr() {
    return weighted_abr;
  }

  /**
   * Sets the value of the 'weighted_abr' field.
   * @param value the value to set.
   */
  public void setWeightedAbr(java.lang.Integer value) {
    this.weighted_abr = value;
  }

  /** Creates a new quality_metrics RecordBuilder */
  public static com.twc.bigdata.views.avro.quality_metrics.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.quality_metrics.Builder();
  }
  
  /** Creates a new quality_metrics RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.quality_metrics.Builder newBuilder(com.twc.bigdata.views.avro.quality_metrics.Builder other) {
    return new com.twc.bigdata.views.avro.quality_metrics.Builder(other);
  }
  
  /** Creates a new quality_metrics RecordBuilder by copying an existing quality_metrics instance */
  public static com.twc.bigdata.views.avro.quality_metrics.Builder newBuilder(com.twc.bigdata.views.avro.quality_metrics other) {
    return new com.twc.bigdata.views.avro.quality_metrics.Builder(other);
  }
  
  /**
   * RecordBuilder for quality_metrics instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<quality_metrics>
    implements org.apache.avro.data.RecordBuilder<quality_metrics> {

    private java.lang.Integer seconds_below_abrx;
    private java.lang.Integer startup_msec;
    private java.lang.Integer abandon_time;
    private java.lang.Integer count_buffer_events;
    private java.lang.Integer buffer_msec;
    private java.lang.Integer weighted_abr;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.quality_metrics.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.quality_metrics.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing quality_metrics instance */
    private Builder(com.twc.bigdata.views.avro.quality_metrics other) {
            super(com.twc.bigdata.views.avro.quality_metrics.SCHEMA$);
      if (isValidValue(fields()[0], other.seconds_below_abrx)) {
        this.seconds_below_abrx = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.seconds_below_abrx);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startup_msec)) {
        this.startup_msec = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.startup_msec);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.abandon_time)) {
        this.abandon_time = (java.lang.Integer) data().deepCopy(fields()[2].schema(), other.abandon_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.count_buffer_events)) {
        this.count_buffer_events = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.count_buffer_events);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buffer_msec)) {
        this.buffer_msec = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.buffer_msec);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.weighted_abr)) {
        this.weighted_abr = (java.lang.Integer) data().deepCopy(fields()[5].schema(), other.weighted_abr);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'seconds_below_abrx' field */
    public java.lang.Integer getSecondsBelowAbrx() {
      return seconds_below_abrx;
    }
    
    /** Sets the value of the 'seconds_below_abrx' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setSecondsBelowAbrx(java.lang.Integer value) {
      validate(fields()[0], value);
      this.seconds_below_abrx = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'seconds_below_abrx' field has been set */
    public boolean hasSecondsBelowAbrx() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'seconds_below_abrx' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearSecondsBelowAbrx() {
      seconds_below_abrx = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'startup_msec' field */
    public java.lang.Integer getStartupMsec() {
      return startup_msec;
    }
    
    /** Sets the value of the 'startup_msec' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setStartupMsec(java.lang.Integer value) {
      validate(fields()[1], value);
      this.startup_msec = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'startup_msec' field has been set */
    public boolean hasStartupMsec() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'startup_msec' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearStartupMsec() {
      startup_msec = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'abandon_time' field */
    public java.lang.Integer getAbandonTime() {
      return abandon_time;
    }
    
    /** Sets the value of the 'abandon_time' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setAbandonTime(java.lang.Integer value) {
      validate(fields()[2], value);
      this.abandon_time = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'abandon_time' field has been set */
    public boolean hasAbandonTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'abandon_time' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearAbandonTime() {
      abandon_time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'count_buffer_events' field */
    public java.lang.Integer getCountBufferEvents() {
      return count_buffer_events;
    }
    
    /** Sets the value of the 'count_buffer_events' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setCountBufferEvents(java.lang.Integer value) {
      validate(fields()[3], value);
      this.count_buffer_events = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'count_buffer_events' field has been set */
    public boolean hasCountBufferEvents() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'count_buffer_events' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearCountBufferEvents() {
      count_buffer_events = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'buffer_msec' field */
    public java.lang.Integer getBufferMsec() {
      return buffer_msec;
    }
    
    /** Sets the value of the 'buffer_msec' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setBufferMsec(java.lang.Integer value) {
      validate(fields()[4], value);
      this.buffer_msec = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'buffer_msec' field has been set */
    public boolean hasBufferMsec() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'buffer_msec' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearBufferMsec() {
      buffer_msec = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'weighted_abr' field */
    public java.lang.Integer getWeightedAbr() {
      return weighted_abr;
    }
    
    /** Sets the value of the 'weighted_abr' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder setWeightedAbr(java.lang.Integer value) {
      validate(fields()[5], value);
      this.weighted_abr = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'weighted_abr' field has been set */
    public boolean hasWeightedAbr() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'weighted_abr' field */
    public com.twc.bigdata.views.avro.quality_metrics.Builder clearWeightedAbr() {
      weighted_abr = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public quality_metrics build() {
      try {
        quality_metrics record = new quality_metrics();
        record.seconds_below_abrx = fieldSetFlags()[0] ? this.seconds_below_abrx : (java.lang.Integer) defaultValue(fields()[0]);
        record.startup_msec = fieldSetFlags()[1] ? this.startup_msec : (java.lang.Integer) defaultValue(fields()[1]);
        record.abandon_time = fieldSetFlags()[2] ? this.abandon_time : (java.lang.Integer) defaultValue(fields()[2]);
        record.count_buffer_events = fieldSetFlags()[3] ? this.count_buffer_events : (java.lang.Integer) defaultValue(fields()[3]);
        record.buffer_msec = fieldSetFlags()[4] ? this.buffer_msec : (java.lang.Integer) defaultValue(fields()[4]);
        record.weighted_abr = fieldSetFlags()[5] ? this.weighted_abr : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
