/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class viewing_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"viewing_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"start_time\",\"type\":[\"long\",\"null\"],\"default\":0},{\"name\":\"end_time\",\"type\":[\"long\",\"null\"],\"default\":0},{\"name\":\"offset\",\"type\":[\"long\",\"null\"],\"default\":0},{\"name\":\"play_seconds\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"seconds_watched\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"furthest_point\",\"type\":[\"int\",\"null\"],\"default\":0},{\"name\":\"stream_failed\",\"type\":[\"int\",\"null\"],\"default\":0}]}");
  @Deprecated public java.lang.Long start_time;
  @Deprecated public java.lang.Long end_time;
  @Deprecated public java.lang.Long offset;
  @Deprecated public java.lang.Integer play_seconds;
  @Deprecated public java.lang.Integer seconds_watched;
  @Deprecated public java.lang.Integer furthest_point;
  @Deprecated public java.lang.Integer stream_failed;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return start_time;
    case 1: return end_time;
    case 2: return offset;
    case 3: return play_seconds;
    case 4: return seconds_watched;
    case 5: return furthest_point;
    case 6: return stream_failed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: start_time = (java.lang.Long)value$; break;
    case 1: end_time = (java.lang.Long)value$; break;
    case 2: offset = (java.lang.Long)value$; break;
    case 3: play_seconds = (java.lang.Integer)value$; break;
    case 4: seconds_watched = (java.lang.Integer)value$; break;
    case 5: furthest_point = (java.lang.Integer)value$; break;
    case 6: stream_failed = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'start_time' field.
   */
  public java.lang.Long getStartTime() {
    return start_time;
  }

  /**
   * Sets the value of the 'start_time' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.Long value) {
    this.start_time = value;
  }

  /**
   * Gets the value of the 'end_time' field.
   */
  public java.lang.Long getEndTime() {
    return end_time;
  }

  /**
   * Sets the value of the 'end_time' field.
   * @param value the value to set.
   */
  public void setEndTime(java.lang.Long value) {
    this.end_time = value;
  }

  /**
   * Gets the value of the 'offset' field.
   */
  public java.lang.Long getOffset() {
    return offset;
  }

  /**
   * Sets the value of the 'offset' field.
   * @param value the value to set.
   */
  public void setOffset(java.lang.Long value) {
    this.offset = value;
  }

  /**
   * Gets the value of the 'play_seconds' field.
   */
  public java.lang.Integer getPlaySeconds() {
    return play_seconds;
  }

  /**
   * Sets the value of the 'play_seconds' field.
   * @param value the value to set.
   */
  public void setPlaySeconds(java.lang.Integer value) {
    this.play_seconds = value;
  }

  /**
   * Gets the value of the 'seconds_watched' field.
   */
  public java.lang.Integer getSecondsWatched() {
    return seconds_watched;
  }

  /**
   * Sets the value of the 'seconds_watched' field.
   * @param value the value to set.
   */
  public void setSecondsWatched(java.lang.Integer value) {
    this.seconds_watched = value;
  }

  /**
   * Gets the value of the 'furthest_point' field.
   */
  public java.lang.Integer getFurthestPoint() {
    return furthest_point;
  }

  /**
   * Sets the value of the 'furthest_point' field.
   * @param value the value to set.
   */
  public void setFurthestPoint(java.lang.Integer value) {
    this.furthest_point = value;
  }

  /**
   * Gets the value of the 'stream_failed' field.
   */
  public java.lang.Integer getStreamFailed() {
    return stream_failed;
  }

  /**
   * Sets the value of the 'stream_failed' field.
   * @param value the value to set.
   */
  public void setStreamFailed(java.lang.Integer value) {
    this.stream_failed = value;
  }

  /** Creates a new viewing_info RecordBuilder */
  public static com.twc.bigdata.views.avro.viewing_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.viewing_info.Builder();
  }
  
  /** Creates a new viewing_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.viewing_info.Builder newBuilder(com.twc.bigdata.views.avro.viewing_info.Builder other) {
    return new com.twc.bigdata.views.avro.viewing_info.Builder(other);
  }
  
  /** Creates a new viewing_info RecordBuilder by copying an existing viewing_info instance */
  public static com.twc.bigdata.views.avro.viewing_info.Builder newBuilder(com.twc.bigdata.views.avro.viewing_info other) {
    return new com.twc.bigdata.views.avro.viewing_info.Builder(other);
  }
  
  /**
   * RecordBuilder for viewing_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<viewing_info>
    implements org.apache.avro.data.RecordBuilder<viewing_info> {

    private java.lang.Long start_time;
    private java.lang.Long end_time;
    private java.lang.Long offset;
    private java.lang.Integer play_seconds;
    private java.lang.Integer seconds_watched;
    private java.lang.Integer furthest_point;
    private java.lang.Integer stream_failed;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.viewing_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.viewing_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing viewing_info instance */
    private Builder(com.twc.bigdata.views.avro.viewing_info other) {
            super(com.twc.bigdata.views.avro.viewing_info.SCHEMA$);
      if (isValidValue(fields()[0], other.start_time)) {
        this.start_time = (java.lang.Long) data().deepCopy(fields()[0].schema(), other.start_time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.end_time)) {
        this.end_time = (java.lang.Long) data().deepCopy(fields()[1].schema(), other.end_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.offset)) {
        this.offset = (java.lang.Long) data().deepCopy(fields()[2].schema(), other.offset);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.play_seconds)) {
        this.play_seconds = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.play_seconds);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.seconds_watched)) {
        this.seconds_watched = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.seconds_watched);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.furthest_point)) {
        this.furthest_point = (java.lang.Integer) data().deepCopy(fields()[5].schema(), other.furthest_point);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.stream_failed)) {
        this.stream_failed = (java.lang.Integer) data().deepCopy(fields()[6].schema(), other.stream_failed);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'start_time' field */
    public java.lang.Long getStartTime() {
      return start_time;
    }
    
    /** Sets the value of the 'start_time' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setStartTime(java.lang.Long value) {
      validate(fields()[0], value);
      this.start_time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'start_time' field has been set */
    public boolean hasStartTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'start_time' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearStartTime() {
      start_time = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'end_time' field */
    public java.lang.Long getEndTime() {
      return end_time;
    }
    
    /** Sets the value of the 'end_time' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setEndTime(java.lang.Long value) {
      validate(fields()[1], value);
      this.end_time = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'end_time' field has been set */
    public boolean hasEndTime() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'end_time' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearEndTime() {
      end_time = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'offset' field */
    public java.lang.Long getOffset() {
      return offset;
    }
    
    /** Sets the value of the 'offset' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setOffset(java.lang.Long value) {
      validate(fields()[2], value);
      this.offset = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'offset' field has been set */
    public boolean hasOffset() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'offset' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearOffset() {
      offset = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'play_seconds' field */
    public java.lang.Integer getPlaySeconds() {
      return play_seconds;
    }
    
    /** Sets the value of the 'play_seconds' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setPlaySeconds(java.lang.Integer value) {
      validate(fields()[3], value);
      this.play_seconds = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'play_seconds' field has been set */
    public boolean hasPlaySeconds() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'play_seconds' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearPlaySeconds() {
      play_seconds = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'seconds_watched' field */
    public java.lang.Integer getSecondsWatched() {
      return seconds_watched;
    }
    
    /** Sets the value of the 'seconds_watched' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setSecondsWatched(java.lang.Integer value) {
      validate(fields()[4], value);
      this.seconds_watched = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'seconds_watched' field has been set */
    public boolean hasSecondsWatched() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'seconds_watched' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearSecondsWatched() {
      seconds_watched = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'furthest_point' field */
    public java.lang.Integer getFurthestPoint() {
      return furthest_point;
    }
    
    /** Sets the value of the 'furthest_point' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setFurthestPoint(java.lang.Integer value) {
      validate(fields()[5], value);
      this.furthest_point = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'furthest_point' field has been set */
    public boolean hasFurthestPoint() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'furthest_point' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearFurthestPoint() {
      furthest_point = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'stream_failed' field */
    public java.lang.Integer getStreamFailed() {
      return stream_failed;
    }
    
    /** Sets the value of the 'stream_failed' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder setStreamFailed(java.lang.Integer value) {
      validate(fields()[6], value);
      this.stream_failed = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'stream_failed' field has been set */
    public boolean hasStreamFailed() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'stream_failed' field */
    public com.twc.bigdata.views.avro.viewing_info.Builder clearStreamFailed() {
      stream_failed = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public viewing_info build() {
      try {
        viewing_info record = new viewing_info();
        record.start_time = fieldSetFlags()[0] ? this.start_time : (java.lang.Long) defaultValue(fields()[0]);
        record.end_time = fieldSetFlags()[1] ? this.end_time : (java.lang.Long) defaultValue(fields()[1]);
        record.offset = fieldSetFlags()[2] ? this.offset : (java.lang.Long) defaultValue(fields()[2]);
        record.play_seconds = fieldSetFlags()[3] ? this.play_seconds : (java.lang.Integer) defaultValue(fields()[3]);
        record.seconds_watched = fieldSetFlags()[4] ? this.seconds_watched : (java.lang.Integer) defaultValue(fields()[4]);
        record.furthest_point = fieldSetFlags()[5] ? this.furthest_point : (java.lang.Integer) defaultValue(fields()[5]);
        record.stream_failed = fieldSetFlags()[6] ? this.stream_failed : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
