/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twc.bigdata.views.avro;  
@SuppressWarnings("all")
public class vod_content_info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"vod_content_info\",\"namespace\":\"com.twc.bigdata.views.avro\",\"fields\":[{\"name\":\"product_provider\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"network\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  @Deprecated public java.lang.CharSequence product_provider;
  @Deprecated public java.lang.CharSequence network;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_provider;
    case 1: return network;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_provider = (java.lang.CharSequence)value$; break;
    case 1: network = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'product_provider' field.
   */
  public java.lang.CharSequence getProductProvider() {
    return product_provider;
  }

  /**
   * Sets the value of the 'product_provider' field.
   * @param value the value to set.
   */
  public void setProductProvider(java.lang.CharSequence value) {
    this.product_provider = value;
  }

  /**
   * Gets the value of the 'network' field.
   */
  public java.lang.CharSequence getNetwork() {
    return network;
  }

  /**
   * Sets the value of the 'network' field.
   * @param value the value to set.
   */
  public void setNetwork(java.lang.CharSequence value) {
    this.network = value;
  }

  /** Creates a new vod_content_info RecordBuilder */
  public static com.twc.bigdata.views.avro.vod_content_info.Builder newBuilder() {
    return new com.twc.bigdata.views.avro.vod_content_info.Builder();
  }
  
  /** Creates a new vod_content_info RecordBuilder by copying an existing Builder */
  public static com.twc.bigdata.views.avro.vod_content_info.Builder newBuilder(com.twc.bigdata.views.avro.vod_content_info.Builder other) {
    return new com.twc.bigdata.views.avro.vod_content_info.Builder(other);
  }
  
  /** Creates a new vod_content_info RecordBuilder by copying an existing vod_content_info instance */
  public static com.twc.bigdata.views.avro.vod_content_info.Builder newBuilder(com.twc.bigdata.views.avro.vod_content_info other) {
    return new com.twc.bigdata.views.avro.vod_content_info.Builder(other);
  }
  
  /**
   * RecordBuilder for vod_content_info instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<vod_content_info>
    implements org.apache.avro.data.RecordBuilder<vod_content_info> {

    private java.lang.CharSequence product_provider;
    private java.lang.CharSequence network;

    /** Creates a new Builder */
    private Builder() {
      super(com.twc.bigdata.views.avro.vod_content_info.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.twc.bigdata.views.avro.vod_content_info.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing vod_content_info instance */
    private Builder(com.twc.bigdata.views.avro.vod_content_info other) {
            super(com.twc.bigdata.views.avro.vod_content_info.SCHEMA$);
      if (isValidValue(fields()[0], other.product_provider)) {
        this.product_provider = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.product_provider);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.network)) {
        this.network = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.network);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'product_provider' field */
    public java.lang.CharSequence getProductProvider() {
      return product_provider;
    }
    
    /** Sets the value of the 'product_provider' field */
    public com.twc.bigdata.views.avro.vod_content_info.Builder setProductProvider(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.product_provider = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'product_provider' field has been set */
    public boolean hasProductProvider() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'product_provider' field */
    public com.twc.bigdata.views.avro.vod_content_info.Builder clearProductProvider() {
      product_provider = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'network' field */
    public java.lang.CharSequence getNetwork() {
      return network;
    }
    
    /** Sets the value of the 'network' field */
    public com.twc.bigdata.views.avro.vod_content_info.Builder setNetwork(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.network = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'network' field has been set */
    public boolean hasNetwork() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'network' field */
    public com.twc.bigdata.views.avro.vod_content_info.Builder clearNetwork() {
      network = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public vod_content_info build() {
      try {
        vod_content_info record = new vod_content_info();
        record.product_provider = fieldSetFlags()[0] ? this.product_provider : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.network = fieldSetFlags()[1] ? this.network : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
